# Generated by Django 5.2.4 on 2025-08-04 00:16

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('empresas', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='FormaPagamento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('descricao', models.CharField(max_length=100)),
                ('tipo', models.CharField(choices=[('dinheiro', 'Dinheiro'), ('cartao_credito', 'Cartão de Crédito'), ('cartao_debito', 'Cartão de Débito'), ('boleto', 'Boleto'), ('pix', 'PIX')], max_length=20)),
                ('is_active', models.BooleanField(default=True)),
                ('empresa', models.ForeignKey(db_constraint=False, on_delete=django.db.models.deletion.PROTECT, to='empresas.empresa')),
            ],
        ),
    ]
