# Generated by Django 5.2.4 on 2025-08-04 00:16

import django.db.models.deletion
import funcionarios.models
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('empresas', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Funcionario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cpf', models.CharField(max_length=14, unique=True)),
                ('nome_completo', models.CharField(max_length=255)),
                ('data_nascimento', models.DateField()),
                ('sexo', models.CharField(choices=[('M', 'Masculino'), ('F', 'Feminino'), ('O', 'Outro')], max_length=1)),
                ('nacionalidade', models.CharField(default='Brasileira', max_length=50)),
                ('endereco', models.CharField(max_length=255, verbose_name='Logradouro')),
                ('numero', models.CharField(default='S/N', max_length=10, verbose_name='Número')),
                ('bairro', models.CharField(default='Bairro não informado', max_length=100, verbose_name='Bairro')),
                ('cidade', models.CharField(default='Cidade não informada', max_length=100, verbose_name='Cidade')),
                ('estado', models.CharField(default='XX', max_length=2, validators=[funcionarios.models.estado_validator], verbose_name='Estado')),
                ('cep', models.CharField(blank=True, default='00000-000', max_length=9, null=True, verbose_name='CEP')),
                ('estado_civil', models.CharField(choices=[('S', 'Solteiro'), ('C', 'Casado'), ('D', 'Divorciado'), ('V', 'Viúvo'), ('U', 'União Estável')], max_length=1)),
                ('grau_instrucao', models.CharField(choices=[('FI', 'Fundamental Incompleto'), ('FC', 'Fundamental Completo'), ('MI', 'Médio Incompleto'), ('MC', 'Médio Completo'), ('SI', 'Superior Incompleto'), ('SC', 'Superior Completo'), ('PG', 'Pós-Graduação'), ('ME', 'Mestrado'), ('DO', 'Doutorado')], max_length=2)),
                ('data_admissao', models.DateField()),
                ('matricula', models.CharField(max_length=20, unique=True)),
                ('cargo_funcao', models.CharField(max_length=100)),
                ('tipo_contrato', models.CharField(choices=[('C', 'CLT'), ('P', 'Pessoa Jurídica'), ('T', 'Temporário'), ('E', 'Estágio')], max_length=1)),
                ('jornada_trabalho', models.CharField(max_length=50)),
                ('categoria', models.CharField(choices=[('ADM', 'Administrativo'), ('TEC', 'Técnico'), ('GES', 'Gestão'), ('OPE', 'Operacional')], max_length=3)),
                ('salario', models.DecimalField(decimal_places=2, max_digits=10)),
                ('forma_pagamento', models.CharField(choices=[('D', 'Dinheiro'), ('T', 'Transferência Bancária'), ('P', 'Pix'), ('C', 'Cheque')], max_length=1)),
                ('is_active', models.BooleanField(default=True)),
                ('empresa', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.PROTECT, to='empresas.empresa')),
            ],
        ),
    ]
