"""
Django settings for multipla_teste project.

Generated by 'django-admin startproject' using Django 4.2.14.

For more information on this file, see
https://docs.djangoproject.com/en/4.2/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/4.2/ref/settings/
"""

from pathlib import Path
from datetime import timedelta
import logging
import os
from corsheaders.defaults import default_headers


logger = logging.getLogger(__name__)
# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/4.2/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = 'django-insecure-$-cdbts1n0p1!d%qy^a#8=c*n%0f#26mvmw^3ivglzzq4sx)df'

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = True

ALLOWED_HOSTS = []
ALLOWED_HOSTS = [
    '127.0.0.1',
    'localhost',
    'testserver',
    'financeiro.multipla.tec.br',
    '5.78.120.45',
    "127.0.1", 
    "0.0.0.0"
]


# Application definition

INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'rest_framework.authtoken',
    'rest_framework_simplejwt',
    'django_extensions',
    'django_filters',
    'corsheaders',
    'fornecedores',
    'clientes',
    'contratos',
    'projetos',
    'pagamentos',
    'funcionarios',
    'contas_pagar',
    'usuarios',
    'empresas',
    'financeiro',
    'notifications',
]

REST_FRAMEWORK = {
    
    #'empresas',
    'empresas.apps.EmpresasConfig',
    'financeiro',
    'funcionarios',
    'relatorios',
    'notifications',
}

REST_FRAMEWORK = {
    'DEFAULT_PARSER_CLASSES': [
        'rest_framework.parsers.JSONParser',
        'rest_framework.parsers.FormParser',
        'rest_framework.parsers.MultiPartParser',
    ],

    'DEFAULT_AUTHENTICATION_CLASSES': (
        'rest_framework_simplejwt.authentication.JWTAuthentication',
        
    ),
}

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'multipla_teste.tenant_middleware.TenantMiddleware',

    'django.middleware.security.SecurityMiddleware',
    'corsheaders.middleware.CorsMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
    'corsheaders.middleware.CorsMiddleware',
    'django.middleware.common.CommonMiddleware',
    #'multipla_teste.middleware.TokenValidationMiddleware',
]

logger.info("Middlewares configurados: %s", MIDDLEWARE)

ROOT_URLCONF = 'multipla_teste.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

DATABASE_ROUTERS = [
  'multipla_teste.tenant_router.TenantRouter',
]


WSGI_APPLICATION = 'multipla_teste.wsgi.application'

CORS_ALLOWED_ORIGINS = [
    'http://localhost:3000',  # Substitua pela porta
    'http://192.168.0.71:3000',
    'https://financeiro.multipla.tec.br',
    'http://localhost:5173',
]

# Permite o header X-Filial-ID na preflight response
CORS_ALLOW_HEADERS = list(default_headers) + [
    "x-company-id",
]

SIMPLE_JWT = {
    'ACCESS_TOKEN_LIFETIME': timedelta(minutes=1440),  # 24h
    # ... outras configurações
}


# Database
# https://docs.djangoproject.com/en/4.2/ref/settings/#databases

DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.postgresql',
        'NAME': 'multipla_financeiro',
        'USER': 'multipla',
        'PASSWORD': 'multipla',
        'HOST': 'localhost',  # Ou o endereço do seu servidor PostgreSQL
        'PORT': '5432',    # Porta padrão do PostgreSQL
        'NAME': 'multipla_financeiro_novo',
        'USER': 'multipla',
        'PASSWORD': 'multipla',
        'HOST': 'localhost',
        'PORT': '5432',
        # Mantém configurações simples e compatíveis
        'CONN_MAX_AGE': 60, 
    }
}


# Password validation
# https://docs.djangoproject.com/en/4.2/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]



#upload handle
# Configurações para arquivos de mídia
MEDIA_URL = '/media/'
MEDIA_ROOT = os.path.join(BASE_DIR, 'media')

# Limites para uploads de arquivos (opcional)
DATA_UPLOAD_MAX_MEMORY_SIZE = 5242880  # 5MB
FILE_UPLOAD_MAX_MEMORY_SIZE = 5242880  # 5MB


# Internationalization
# https://docs.djangoproject.com/en/4.2/topics/i18n/

LANGUAGE_CODE = 'pt-br'

TIME_ZONE = 'America/Sao_Paulo'

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/4.2/howto/static-files/

STATIC_URL = 'static/'

# Default primary key field type
# https://docs.djangoproject.com/en/4.2/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'

# Em settings.py, adicione:
LOGGING = {
    'version': 1,
    'disable_existing_loggers': False,
    'handlers': {
        'console': {
            'class': 'logging.StreamHandler',
        },
    },
    'loggers': {
        'multipla_teste': {
            'handlers': ['console'],
            'level': 'DEBUG',
        },
    },
}
