# Generated by Django 5.2.4 on 2025-08-04 00:16

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('empresas', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='PerfilUsuario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('empresa_padrao', models.ForeignKey(help_text='Empresa padrão', on_delete=django.db.models.deletion.PROTECT, to='empresas.empresa')),
                ('empresas_acessiveis', models.ManyToManyField(blank=True, related_name='usuarios', to='empresas.empresa')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='UsuarioEmpresaRole',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('role', models.CharField(choices=[('admin', 'Administrador'), ('financeiro', 'Financeiro'), ('leitura', 'Somente Leitura')], default='leitura', max_length=20)),
                ('empresa', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='empresas.empresa')),
                ('perfil_usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='usuarios.perfilusuario')),
            ],
            options={
                'verbose_name': 'Papel de Usuário por Empresa',
                'verbose_name_plural': 'Papéis de Usuários por Empresa',
                'unique_together': {('perfil_usuario', 'empresa')},
            },
        ),
    ]
