# Generated by Django 5.2.4 on 2025-08-04 00:16

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('empresas', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ContaFinanceira',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mascara_conta', models.CharField(max_length=14, unique=True, validators=[django.core.validators.RegexValidator(message='A máscara deve seguir o formato 1.11.111.1111', regex='^\\d\\.\\d{2}\\.\\d{3}\\.\\d{4}$')])),
                ('descricao', models.CharField(max_length=100)),
                ('is_active', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='CentroCusto',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('descricao', models.CharField(max_length=100)),
                ('mascara_centro_custo', models.CharField(max_length=3)),
                ('is_active', models.BooleanField(default=True)),
                ('empresa', models.ForeignKey(db_constraint=False, on_delete=django.db.models.deletion.PROTECT, to='empresas.empresa')),
            ],
            options={
                'verbose_name': 'Centro de Custo',
                'verbose_name_plural': 'Centros de Custo',
                'unique_together': {('empresa', 'mascara_centro_custo')},
            },
        ),
    ]
