# Generated by Django 5.2.4 on 2025-08-04 00:16

import django.db.models.deletion
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('clientes', '0001_initial'),
        ('contratos', '0001_initial'),
        ('empresas', '0001_initial'),
        ('financeiro', '0001_initial'),
        ('fornecedores', '0001_initial'),
        ('funcionarios', '0001_initial'),
        ('pagamentos', '0001_initial'),
        ('projetos', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ContaAPagar',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('pendente', 'Pendente'), ('pago', 'Pago'), ('estornado', 'Estornado')], default='pendente', max_length=20)),
                ('data_pagamento', models.DateField()),
                ('competencia', models.DateField()),
                ('valor_total', models.DecimalField(decimal_places=2, max_digits=10)),
                ('is_active', models.BooleanField(default=True)),
                ('diferenca', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=10)),
                ('justificativa_diferenca', models.TextField(blank=True, null=True)),
                ('centro_custo', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='financeiro.centrocusto')),
                ('conta_financeira', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='financeiro.contafinanceira')),
                ('contrato', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='contas_pagar', to='contratos.contrato')),
                ('empresa', models.ForeignKey(db_constraint=False, on_delete=django.db.models.deletion.PROTECT, to='empresas.empresa')),
                ('forma_pagamento', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='pagamentos.formapagamento')),
            ],
        ),
        migrations.CreateModel(
            name='ContaAReceber',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('pendente', 'Pendente'), ('recebido', 'Recebido'), ('estornado', 'Estornado')], default='pendente', max_length=20)),
                ('data_recebimento', models.DateField()),
                ('competencia', models.DateField()),
                ('valor_total', models.DecimalField(decimal_places=2, max_digits=10)),
                ('is_active', models.BooleanField(default=True)),
                ('diferenca', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=10)),
                ('justificativa_diferenca', models.TextField(blank=True, null=True)),
                ('centro_custo', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='financeiro.centrocusto')),
                ('conta_financeira', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='financeiro.contafinanceira')),
                ('contrato', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='contas_receber', to='contratos.contrato')),
                ('empresa', models.ForeignKey(db_constraint=False, on_delete=django.db.models.deletion.PROTECT, to='empresas.empresa')),
                ('forma_pagamento', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='pagamentos.formapagamento')),
            ],
            options={
                'ordering': ['-data_recebimento'],
            },
        ),
        migrations.CreateModel(
            name='ContaPagarAvulso',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo_pagador', models.CharField(choices=[('fornecedor', 'Fornecedor'), ('funcionario', 'Funcionário')], default='fornecedor', max_length=20)),
                ('descricao', models.CharField(max_length=255)),
                ('valor', models.DecimalField(decimal_places=2, max_digits=10)),
                ('data_pagamento', models.DateField()),
                ('competencia', models.CharField(max_length=7)),
                ('is_active', models.BooleanField(default=True)),
                ('status', models.CharField(choices=[('pendente', 'Pendente'), ('pago', 'Pago'), ('estornado', 'Estornado')], default='pendente', max_length=20)),
                ('centro_custo', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='financeiro.centrocusto')),
                ('conta_financeira', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='financeiro.contafinanceira')),
                ('empresa', models.ForeignKey(db_constraint=False, on_delete=django.db.models.deletion.PROTECT, to='empresas.empresa')),
                ('fornecedor', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='fornecedores.fornecedor')),
                ('funcionario', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='funcionarios.funcionario')),
                ('projetos', models.ManyToManyField(blank=True, to='projetos.projeto')),
            ],
        ),
        migrations.CreateModel(
            name='ContaReceberAvulso',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('descricao', models.CharField(max_length=255)),
                ('valor', models.DecimalField(decimal_places=2, max_digits=10)),
                ('data_recebimento', models.DateField()),
                ('competencia', models.CharField(max_length=7)),
                ('is_active', models.BooleanField(default=True)),
                ('status', models.CharField(choices=[('pendente', 'Pendente'), ('recebido', 'Recebido'), ('estornado', 'Estornado')], default='pendente', max_length=20)),
                ('centro_custo', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='financeiro.centrocusto')),
                ('cliente', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='clientes.cliente')),
                ('conta_financeira', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='financeiro.contafinanceira')),
                ('empresa', models.ForeignKey(db_constraint=False, on_delete=django.db.models.deletion.PROTECT, to='empresas.empresa')),
                ('projetos', models.ManyToManyField(blank=True, to='projetos.projeto')),
            ],
        ),
        migrations.CreateModel(
            name='ProjetoConta',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('valor', models.DecimalField(decimal_places=2, max_digits=10)),
                ('conta', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='contas_pagar.contareceberavulso')),
                ('projeto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='projetos.projeto')),
            ],
        ),
        migrations.CreateModel(
            name='ProjetoContaPagar',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('valor', models.DecimalField(decimal_places=2, max_digits=10)),
                ('conta', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='contas_pagar.contapagaravulso')),
                ('projeto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='projetos.projeto')),
            ],
        ),
    ]
