# Generated by Django 5.2.4 on 2025-08-04 00:16

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('contratos', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='NotificacaoVencimento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo', models.CharField(choices=[('vencimento_2_dias', 'Vencimento em 2 dias'), ('vencimento_hoje', 'Vencimento hoje'), ('vencimento_atrasado', 'Vencimento em atraso')], max_length=20)),
                ('titulo', models.CharField(max_length=200)),
                ('mensagem', models.TextField()),
                ('lida', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('projecao', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='contratos.projecaofaturamento')),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
                'unique_together': {('usuario', 'projecao', 'tipo')},
            },
        ),
    ]
